{% set name = "csaps" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/csaps-{{ version }}.tar.gz
  sha256: 977644db0aa1a10b9e99c7159ea7f70b064310b8fc4bfd8fc6d293b0bfc3c385

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0
    - numpy >=1.11.0,<1.20.0
    - scipy >=1.0.0,<1.6.0

test:
  imports:
    - csaps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/espdev/csaps
  summary: Cubic spline approximation (smoothing)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smithsp
    - kalling
